version: "3"
services:
  test_database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mountaindb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306 # environment docker testing mysql port
  test_application:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - test_database
