server:
  port: 8080
spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/mountaindb?autoReconnect=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.mountain.backend.database.custom.CustomDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
  resources:
    static-locations: ${project.base-dir}/src/main/resources/static/
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: G7b1N6bHENr0f73Y1q_7
            client-secret: 5bXDBe9Rc5
            redirectUri: "{baseUrl}/login/oauth2/code/naver"
            authorization_grant_type: authorization_code
            scope:
              - name
              - email
              - phone_number
              - nickname
            client-name: naver
          kakao:
            client-id: b98599866f3a2188682e3ddcc5e71f78
            client-secret: 1u8yJ2FfQwHCBWWKHhbDVHgUUS4Nmt9o
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
          facebook:
            client-id: 1781188735603089
            client-secret: 13dca54e27c1b40c2befcdf61c9a31f0
            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
app:
  auth:
    tokenSecret: TOq;tw{fx}2,hPW&4Qw(&8]d`c$ZN#
    tokenExpirationSeconds: 3600