server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mountaindb?autoReconnect=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.mountain.backend.database.custom.CustomDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
  resources:
    static-locations: ${project.base-dir}/src/main/static/
app:
  auth:
    tokenSecret: TOq;tw{fx}2,hPW&4Qw(&8]d`c$ZN#
    tokenExpirationSeconds: 3600